server:
  port: ${SERVER_PORT}

---

spring:
  profiles: aws
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database: mysql
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERID}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    stream:
      kafka:
        binder:
          brokers: aeae609db1ed14033bee10d12a9ff8b2-534726741.ap-northeast-2.elb.amazonaws.com:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: Lecture
          destination: moine
          contentType: application/json
        event-out:
          destination: moine
          contentType: application/json

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    org.springframework.cloud: debug