server:
  port: ${SERVER_PORT}

---
spring:
  session:
    jdbc:
      initialize-schema: always
  profiles:
    active: aws
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERID}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

spring.cloud.stream:
  kafka:
    binder:
      brokers: moine-kafka-0.moine-kafka-headless.moine.svc.cluster.local:9092
  bindings:
    input:
      destination: conatus
      contentType: application/json
      group: Group
    output:
      destination: conatus
      contentType: application/json
      group: Group

logging:
  level:
    org.hibernate.type: trace
    org.springframework.cloud: debug

ping:
  string: ${MSG}