server:
  port: 8080

spring:
  session:
    jdbc:
      initialize-schema: always
  config:
    activate:
      on-profile: local
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/Group?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DATABASE_USERID}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: Group
          destination: conatus
          contentType: application/json
        event-out:
          destination: conatus
          contentType: application/json

logging:
  level:
    org.hibernate.type: trace
    org.springframework.cloud: debug