server:
  port: ${SERVER_PORT}

---
spring:
  session:
    jdbc:
      initialize-schema: always
  profiles:
    active: aws
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERID}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  cloud:
    stream:
      kafka:
        binder:
            brokers: 3.38.49.196:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        authTopic:
          group: Lecture
          destination: moine
          contentType: application/json
        lectureTopic:
          destination: moine
          contentType: application/json

logging:
  level:
    org.hibernate.type: trace
    org.springframework.cloud: debug

ping:
  msg: ${PING_MSG}