server:
  port: 8080

---

spring:
  profiles: default
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    database: mysql
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERID}
    password: ${DATABASE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  kafka:
    bootstrap-servers: ${KAFKA_ENDPOINT}
  cloud:
    stream:
      kafka:
        binder:
          brokers: moine-kafka.kafka.svc.cluster.local:9092, moine-kafka-0.moine-kafka-headless.kafka.svc.cluster.local:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: Lecture
          destination: moine
          contentType: application/json
        event-out:
          destination: moine
          contentType: application/json

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace
    org.springframework.cloud: debug


server:
  port: ${SERVER_PORT}
---

spring:
  profiles: aws
  cloud:
    stream:
      kafka:
        binder:
          brokers: moine-kafka.kafka.svc.cluster.local:9092, moine-kafka-0.moine-kafka-headless.kafka.svc.cluster.local:9092
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
                value:
                  serde: org.apache.kafka.common.serialization.Serdes$StringSerde
      bindings:
        event-in:
          group: Lecture
          destination: moine
          contentType: application/json
        event-out:
          destination: moine
          contentType: application/json