apiVersion: apps/v1
kind: Deployment
metadata:
  name: lecture-backend
  labels:
    app: lecture-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lecture-backend
  template:
    metadata:
      labels:
        app: lecture-backend
    spec:
      containers:
        - name: lecture-backend
          image: 357806352922.dkr.ecr.ap-northeast-2.amazonaws.com/moine_lecture:latest
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: lecture-configmap
                  key: database_url
            - name: DATABASE_USERID
              valueFrom:
                configMapKeyRef:
                  name: lecture-configmap
                  key: database_userid
            - name: DATABASE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: lecture-configmap
                  key: database_password
            - name: KAFKA_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: lecture-configmap
                  key: kafka_endpoint
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: lecture-configmap
                  key: server_port
            - name: PING_MSG
              valueFrom:
                configMapKeyRef:
                  name: lecture-configmap
                  key: ping_msg
#          readinessProbe:
#            httpGet:
#              path: '/actuator/health'
#              port: 8080
#            initialDelaySeconds: 10
#            timeoutSeconds: 2
#            periodSeconds: 5
#            failureThreshold: 10
#          livenessProbe:
#            httpGet:
#              path: '/actuator/health'
#              port: 8080
#            initialDelaySeconds: 120
#            timeoutSeconds: 2
#            periodSeconds: 5
#            failureThreshold: 5