apiVersion: apps/v1
kind: Deployment
metadata:
  name: lecture
  labels:
    app: lecture
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lecture
  template:
    metadata:
      labels:
        app: lecture
    spec:
      containers:
        - name: lecture
          image: 357806352922.dkr.ecr.ap-northeast-2.amazonaws.com/moine_lecture:latest
          imagePullPolicy: Always
          env:
            - name: DATABASE_URL
              valueFrom:
                configMapKeyRef:
                  name: moine-backend-configmap
                  key: lecture_database_url
            - name: DATABASE_USERID
              valueFrom:
                configMapKeyRef:
                  name: moine-backend-configmap
                  key: database_userid
            - name: DATABASE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: moine-backend-configmap
                  key: database_password
            - name: KAFKA_BROKERS
              valueFrom:
                configMapKeyRef:
                  name: moine-backend-configmap
                  key: kafka_brokers
            - name: KAFKA_BOOTSTRAP_SERVERS
              valueFrom:
                configMapKeyRef:
                  name: moine-backend-configmap
                  key: kafka_bootstrap_servers
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: moine-backend-configmap
                  key: server_port
            - name: PING_MSG
              valueFrom:
                configMapKeyRef:
                  name: moine-backend-configmap
                  key: ping_msg