apiVersion: apps/v1
kind: Deployment
metadata:
  name: lecture-backend
  labels:
    app: lecture
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lecture
  template:
    metadata:
      labels:
        app: lecture
    spec:
      containers:
        - name: lecture
          image: username/lecture:latest
          ports:
            - containerPort: 8080
          env:
            - name: DATABASE_USERID
              valueFrom:
                configMapKeyRef:
                  name: lecture-configmap
                  key: DATABASE_USERID
            - name: DATABASE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: lecture-configmap
                  key: DATABASE_PASSWORD
            - name: KAFKA_ENDPOINT
              valueFrom:
                configMapKeyRef:
                  name: lecture-configmap
                  key: KAFKA_ENDPOINT
#          readinessProbe:
#            httpGet:
#              path: '/actuator/health'
#              port: 8080
#            initialDelaySeconds: 10
#            timeoutSeconds: 2
#            periodSeconds: 5
#            failureThreshold: 10
#          livenessProbe:
#            httpGet:
#              path: '/actuator/health'
#              port: 8080
#            initialDelaySeconds: 120
#            timeoutSeconds: 2
#            periodSeconds: 5
#            failureThreshold: 5