apiVersion: v1
kind: Service
metadata:
  name: moine-lecture-backend-svc
  labels:
    app: moine-lecture-backend-svc
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      name: moine-lecture-backend
      protocol: TCP
      targetPort: 8080
  selector:
    app: moine-lecture-backend
