apiVersion: v1
kind: Service
metadata:
  name: lecture-backend-svc
  labels:
    app: lecture-backend-svc
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      name: lecture
      protocol: TCP
      targetPort: 8080
  selector:
    app: lecture