apiVersion: v1
kind: Service
metadata:
  name: lecture
  namespace: moine
  labels:
    app: lecture
spec:
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: lecture
  type: LoadBalancer

