apiVersion: v1
kind: Service
metadata:
  name: lecture-svc
  namespace: moine
  labels:
    app: lecture
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: lecture
  type: LoadBalancer

